- name: Set up PXE Server
  hosts: pxeserver
  become: yes
  #vars_files:
  #  - defaults/main.yml

  tasks:
  - name: Set up repo
    replace:
      path: "{{ item }}"
      regexp: 'mirrorlist'
      replace: '#mirrorlist'
    with_items:
      - /etc/yum.repos.d/CentOS-Linux-AppStream.repo
      - /etc/yum.repos.d/CentOS-Linux-BaseOS.repo
  
  - name: Set up repo
    replace:
      path: "{{ item }}"
      regexp: '#baseurl=http://mirror.centos.org'
      replace: 'baseurl=http://vault.centos.org'
    with_items:
      - /etc/yum.repos.d/CentOS-Linux-AppStream.repo
      - /etc/yum.repos.d/CentOS-Linux-BaseOS.repo

  - name: Install softs on CentOS
    yum:
      name:
      - vim
      - wget
      - epel-release
      - httpd
      - tftp-server
      - dhcp-server
      state: present
      update_cache: true

#  - name: Download ISO image CentOS 8.4.2105
#    get_url:
#      url: https://vault.centos.org/8.4.2105/isos/x86_64/CentOS-8.4.2105-x86_64-dvd1.iso
#      dest: ~/CentOS-8.4.2105-x86_64-dvd1.iso
#      mode: '0755'

  - name: Copy ISO image
    copy:
      src: /home/tw4/Downloads/CentOS-8.4.2105-x86_64-dvd1.iso
      dest: /root/
      #remote_src: yes
      directory_mode: yes

  - name: Create ISO directory
    file:
      path: /iso
      state: directory
      mode: '0755'
 
  - name: Mount ISO image
    mount:
      path: /mnt
      src: /root/CentOS-8.4.2105-x86_64-dvd1.iso
      fstype: iso9660
      opts: ro
      state: mounted

  - name: Copy ALL files from /mnt to /iso
    copy:
      src: /mnt/
      dest: /iso
      remote_src: yes
      directory_mode: yes

  - name: Set up httpd config
    template:
      src: pxeboot.conf
      dest: /etc/httpd/conf.d/pxeboot.conf
      owner: root
      group: root
      mode: 0640

  - name: Restart httpd
    ansible.builtin.systemd:
      name: httpd
      state: restarted
      enabled: true

  - name: Create TFTP directory
    file:
      path: /var/lib/tftpboot/pxelinux.cfg
      state: directory
      mode: '0755'
 
  - name: Set up pxelinux
    template:
      src: default
      dest: /var/lib/tftpboot/pxelinux.cfg/default
      owner: root
      group: root
      mode: 0644

  - name: Extract packages syslinux
    shell: rpm2cpio /iso/BaseOS/Packages/syslinux-tftpboot-6.04-5.el8.noarch.rpm | cpio -dimv

  - name: Copy files to TFTP share
    copy:
      src: /home/vagrant/tftpboot/{{ item }}
      dest: /var/lib/tftpboot/{{ item }}
      mode: '0644'
      remote_src: true
    with_items:
      - pxelinux.0
      - ldlinux.c32
      - libmenu.c32
      - libutil.c32
      - menu.c32
      - vesamenu.c32

  - name: Copy initrd and vmlinuz files to TFTP share
    copy:
      src: /iso/images/pxeboot/{{ item }}
      dest: /var/lib/tftpboot/{{ item }}
      mode: '0755'
      remote_src: true
    with_items:
      - initrd.img
      - vmlinuz

  - name: Restart tftp-server
    ansible.builtin.systemd:
      name: tftp.service
      state: restarted
      enabled: true

  - name: Set up dhcp-server
    template:
      src: dhcpd.conf
      dest: /etc/dhcp/dhcpd.conf
      mode: '0644'
  
  - name: Restart dhcp-server
    ansible.builtin.systemd:
      name: dhcpd
      state: restarted
      enabled: true

  - name: Copy ks.cfg
    template:
      src: ks.cfg
      dest: /iso/ks.cfg
      owner: root
      group: root
      mode: 0755
